"""Frequency-domain writers following IBIS Touchstone 2.0 and Keysight CITIfile.

Touchstone writes full single-ended matrices with an explicit 12_21 order for
two ports. CITIfile A.01.01 writes RI arrays and requires the established 50-ohm
convention: an incompatible reference is rejected rather than silently lost.
"""

import csv
import math
from pathlib import Path

from interconnect_studio.core import DataFormatError, Network
from interconnect_studio.io.atomic import atomic_destination
from interconnect_studio.io.text_network import TextDelimiter
from interconnect_studio.io.touchstone import (
    FREQUENCY_SCALE,
    TouchstoneFormat,
    TouchstoneFrequencyUnit,
    _complex_to_pair,
    _format_float,
)


def write_touchstone2(
    network: Network,
    path: str | Path,
    *,
    data_format: TouchstoneFormat = "ri",
    frequency_unit: TouchstoneFrequencyUnit = "hz",
    precision: int = 17,
) -> None:
    """Write an N-port single-ended Network to .ts, preserving real scalar z0."""

    destination = Path(path)
    if destination.suffix.lower() != ".ts":
        raise DataFormatError("Touchstone 2.0 files must use the .ts suffix.")
    _validate_options(network, data_format, frequency_unit, precision)
    reference = _format_float(network.z0.real, precision)
    lines = [
        "! Generated by Interconnect Studio",
        "[Version] 2.0",
        f"# {frequency_unit.upper()} S {data_format.upper()} R {reference}",
        f"[Number of Ports] {network.n_ports}",
    ]
    if network.n_ports == 2:
        lines.append("[Two-Port Data Order] 12_21")
    lines.extend(
        [
            f"[Number of Frequencies] {network.n_freq}",
            "[Reference] " + " ".join([reference] * network.n_ports),
            "[Matrix Format] Full",
            "[Network Data]",
        ]
    )
    scale = FREQUENCY_SCALE[frequency_unit]
    for index, frequency in enumerate(network.frequencies_hz):
        # 1/2 ports: one record; >=3 ports: matrix rows, frequency only on row 1.
        rows: list[str] = []
        for row in range(network.n_ports):
            values = [_format_float(float(frequency) / scale, precision)] if row == 0 else []
            for column in range(network.n_ports):
                pair = _complex_to_pair(network.s[index, row, column], data_format)
                values.extend(_format_float(value, precision) for value in pair)
            rows.append(" ".join(values))
        lines.extend([" ".join(rows)] if network.n_ports <= 2 else rows)
    lines.append("[End]")
    _write_lines(destination, lines)


def write_citifile(network: Network, path: str | Path, *, precision: int = 17) -> None:
    """Write full S[i,j] RI arrays in Hz, requiring z0 exactly 50 ohms.

    No renormalisation is performed by this writer. Use the explicit export
    service option if conversion to a 50-ohm reference is wanted.
    """

    destination = Path(path)
    if destination.suffix.lower() not in {".cti", ".cit"}:
        raise DataFormatError("CITIfile files must use .cti or .cit.")
    if network.z0 != 50.0:
        raise DataFormatError("CITIfile export requires 50 ohms; explicitly renormalise first.")
    if not 1 <= precision <= 17:
        raise DataFormatError("precision must be between 1 and 17.")
    lines = [
        "CITIFILE A.01.01",
        "NAME DATA",
        "COMMENT Generated by Interconnect Studio",
        "COMMENT Reference impedance: 50 ohms",
        f"VAR FREQ MAG {network.n_freq}",
    ]
    positions = [(row, col) for row in range(network.n_ports) for col in range(network.n_ports)]
    lines.extend(f"DATA S[{row + 1},{col + 1}] RI" for row, col in positions)
    lines.append("VAR_LIST_BEGIN")
    lines.extend(_format_float(float(frequency), precision) for frequency in network.frequencies_hz)
    lines.append("VAR_LIST_END")
    for row, col in positions:
        lines.append("BEGIN")
        lines.extend(
            f"{_format_float(value.real, precision)},{_format_float(value.imag, precision)}"
            for value in network.s[:, row, col]
        )
        lines.append("END")
    _write_lines(destination, lines)


def write_text_network(
    network: Network,
    path: str | Path,
    delimiter: TextDelimiter = "comma",
    *,
    frequency_unit: TouchstoneFrequencyUnit = "hz",
) -> None:
    """Write a full RI table; z0 is recorded in an Interconnect Studio comment.

    Comma-delimited fields are CSV-quoted, including S[12,3] column names.
    Other programs may require specifying the recorded reference manually.
    """

    if delimiter not in {"tab", "comma"} or frequency_unit not in FREQUENCY_SCALE:
        raise DataFormatError("Invalid text delimiter or frequency unit.")
    positions = [(row, col) for row in range(network.n_ports) for col in range(network.n_ports)]
    with (
        atomic_destination(Path(path)) as temporary,
        temporary.open("w", encoding="utf-8", newline="") as stream,
    ):
        stream.write(f"! Reference Impedance {network.z0.real:.17g} {network.z0.imag:.17g}\n")
        writer = csv.writer(
            stream, delimiter="," if delimiter == "comma" else "\t", lineterminator="\n"
        )
        header = [f"freq({frequency_unit.upper()})"]
        for row, col in positions:
            name = f"S{row + 1}{col + 1}" if network.n_ports < 10 else f"S[{row + 1},{col + 1}]"
            header.extend([f"{name}(real)", f"{name}(imag)"])
        writer.writerow(header)
        for index, frequency in enumerate(network.frequencies_hz):
            values = [f"{frequency / FREQUENCY_SCALE[frequency_unit]:.17g}"]
            for row, col in positions:
                value = network.s[index, row, col]
                values.extend([f"{value.real:.17g}", f"{value.imag:.17g}"])
            writer.writerow(values)


def _validate_options(network: Network, fmt: str, unit: str, precision: int) -> None:
    if fmt not in {"ri", "ma", "db"} or unit not in FREQUENCY_SCALE:
        raise DataFormatError("Invalid Touchstone format or frequency unit.")
    if not 1 <= precision <= 17:
        raise DataFormatError("precision must be between 1 and 17.")
    if network.z0.imag or not math.isfinite(network.z0.real) or network.z0.real <= 0:
        raise DataFormatError("Touchstone requires a real, positive reference impedance.")


def _write_lines(path: Path, lines: list[str]) -> None:
    with atomic_destination(path) as temporary:
        temporary.write_text("\n".join(lines) + "\n", encoding="ascii")
